server:
  port: 20000
eureka:
  client:
    service-url:
      defaultZone: http://10.10.102.56:8761/eureka
spring:
  application:
    name: Turbine
turbine:
  app-config: bookuser-normal, bookuser-SEMAPHORE, bookuser-nonetimeout, bookuser-circuitBreaker, bookuser-poolsize, bookmanager # 监听的服务id
  aggregator:
    clusterConfig: default # 监听的集群(cluster)
  clusterNameExpression: new String("default") # 集群表达式